FROM aflplusplus/aflplusplus:stable

WORKDIR /build

RUN cat /etc/os-release && \
    add-apt-repository ppa:beineri/opt-qt571-jammy -y && \
    apt-get update -qq && \
    apt-get install -qq cmake build-essential autoconf 


