FROM aflplusplus/aflplusplus:stable
ARG DEBIAN_FRONTEND=noninteractive
RUN cat /etc/os-release && \
    apt update && \
    apt-cache policy libpng && \
    apt install -y libpng-dev p7zip-full p7zip-rar llvm python3-pip && \
    # unlink /etc/localtime && \
    # ln -s /usr/share/zoneinfo/Europe/Moscow /etc/localtime && \
    pip3 install lcov_cobertura

COPY .scripts/ /tmp
COPY .scripts/setup_tests.sh /tmp/.scripts/setup_tests.sh
COPY .scripts/patch.sh /tmp/.scripts/patch.sh
COPY .scripts/radamsa /tmp/.scripts/radamsa

