FROM aflplusplus/aflplusplus:stable

WORKDIR /build

RUN cat /etc/os-release 
RUN add-apt-repository ppa:beineri/opt-qt571-trusty -y 
RUN apt update 
RUN apt install -y cmake build-essential autoconf 


